name: GitHub Actions Demo

on:
  workflow_dispatch:
    inputs:
      name:
        description: 'Name'
        required: false
        default: 'masa'

jobs:
  echo_hello:
    runs-on: ubuntu-latest
    steps: 
      - name: "挨拶"
        run: echo "Nice to meet you!!"

      - name: "名前を言う"
        run: echo "My Name is Taro!!"

      - name: "趣味を話す"
        run: echo "I love programming!!"
        
      - name: print log
        run: echo "Hello! ${{ github.event.inputs.name }}"
